/**
 * PDF Export Module
 * Generates PDF documents from application data
 * Uses jsPDF library (will be loaded from CDN)
 */

// Export documents list to PDF
export async function exportDocumentsToPDF(documents, userProfile) {
    // Check if jsPDF is loaded
    if (typeof window.jspdf === 'undefined') {
        throw new Error('jsPDF library not loaded');
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('viSAM - Document List', 105, 20, { align: 'center' });

    // User info
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    if (userProfile) {
        doc.text(`Name: ${userProfile.name || 'N/A'}`, 20, 35);
        doc.text(`Email: ${userProfile.email || 'N/A'}`, 20, 42);
        doc.text(`Phone: ${userProfile.phone || 'N/A'}`, 20, 49);
    }

    // Date
    const date = new Date().toLocaleDateString('ru-RU');
    doc.text(`Generated: ${date}`, 20, 56);

    // Line separator
    doc.setLineWidth(0.5);
    doc.line(20, 60, 190, 60);

    // Documents table header
    let yPos = 70;
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Documents', 20, yPos);

    yPos += 10;
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');

    // Documents list
    if (documents && documents.length > 0) {
        documents.forEach((doc_item, index) => {
            if (yPos > 270) {
                doc.addPage();
                yPos = 20;
            }

            doc.setFont(undefined, 'bold');
            doc.text(`${index + 1}. ${doc_item.name || doc_item.type || 'Document'}`, 20, yPos);
            yPos += 6;

            doc.setFont(undefined, 'normal');
            if (doc_item.country) {
                doc.text(`   Country: ${doc_item.country}`, 20, yPos);
                yPos += 5;
            }
            if (doc_item.visaType) {
                doc.text(`   Visa Type: ${doc_item.visaType}`, 20, yPos);
                yPos += 5;
            }
            if (doc_item.uploadDate) {
                doc.text(`   Upload Date: ${new Date(doc_item.uploadDate).toLocaleDateString('ru-RU')}`, 20, yPos);
                yPos += 5;
            }
            if (doc_item.status) {
                doc.text(`   Status: ${doc_item.status}`, 20, yPos);
                yPos += 5;
            }

            yPos += 5; // Space between documents
        });
    } else {
        doc.text('No documents found', 20, yPos);
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
        doc.text('Generated by viSAM App', 105, 295, { align: 'center' });
    }

    // Save PDF
    doc.save(`viSAM-documents-${date}.pdf`);
}

// Export single document with details
export async function exportSingleDocumentPDF(document, scanResults) {
    if (typeof window.jspdf === 'undefined') {
        throw new Error('jsPDF library not loaded');
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    // Title
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('Document Analysis Report', 105, 20, { align: 'center' });

    // Document info
    let yPos = 35;
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`Document: ${document.name || 'Unnamed'}`, 20, yPos);
    yPos += 7;
    doc.text(`Type: ${document.type || 'N/A'}`, 20, yPos);
    yPos += 7;
    doc.text(`Country: ${document.country || 'N/A'}`, 20, yPos);
    yPos += 7;
    doc.text(`Date: ${new Date().toLocaleDateString('ru-RU')}`, 20, yPos);

    yPos += 15;

    // Scan results if available
    if (scanResults) {
        doc.setFont(undefined, 'bold');
        doc.text('Analysis Results:', 20, yPos);
        yPos += 10;

        doc.setFont(undefined, 'normal');
        if (scanResults.status) {
            doc.text(`Status: ${scanResults.status}`, 20, yPos);
            yPos += 7;
        }

        if (scanResults.issues && scanResults.issues.length > 0) {
            doc.setFont(undefined, 'bold');
            doc.text('Issues Found:', 20, yPos);
            yPos += 7;
            doc.setFont(undefined, 'normal');

            scanResults.issues.forEach((issue, index) => {
                doc.text(`${index + 1}. ${issue}`, 25, yPos);
                yPos += 6;
            });
        }

        yPos += 5;

        if (scanResults.requirements && scanResults.requirements.length > 0) {
            doc.setFont(undefined, 'bold');
            doc.text('Requirements:', 20, yPos);
            yPos += 7;
            doc.setFont(undefined, 'normal');

            scanResults.requirements.forEach((req, index) => {
                if (yPos > 270) {
                    doc.addPage();
                    yPos = 20;
                }
                doc.text(`${index + 1}. ${req}`, 25, yPos);
                yPos += 6;
            });
        }
    }

    // Save
    doc.save(`viSAM-document-${document.name || 'report'}.pdf`);
}

// Load jsPDF library dynamically
export function loadJsPDF() {
    return new Promise((resolve, reject) => {
        if (typeof window.jspdf !== 'undefined') {
            resolve();
            return;
        }

        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
        script.onload = resolve;
        script.onerror = reject;
        document.head.appendChild(script);
    });
}
